FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY vite.config.ts tsconfig.json tsconfig.node.json tsconfig.workers.json tailwind.config.js postcss.config.js ./
COPY docker-entrypoint.sh .

RUN chmod +x docker-entrypoint.sh

EXPOSE 5173

ENTRYPOINT ["./docker-entrypoint.sh"]