import defaultTheme from 'tailwindcss/defaultTheme'

/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter', ...defaultTheme.fontFamily.sans],
      },
      colors: {
        gnomeBlue1:    '#99c1f1',
        gnomeBlue2:    '#62a0ea',
        gnomeBlue3:    '#3584e4',
        gnomeBlue4:    '#1c71d8',
        gnomeBlue5:    '#1a5fb4',
        gnomeGreen1:   '#8ff0a4',
        gnomeGreen2:    '#57e389',
        gnomeGreen3:    '#33d17a',
        gnomeGreen4:    '#2ec27e',
        gnomeGreen5:    '#26a269',
        gnomeYellow1:   '#f9f06b',
        gnomeYellow2:   '#f8e45c',
        gnomeYellow3:   '#f6d32d',
        gnomeYellow4:   '#f5c211',
        gnomeYellow5:   '#e5a50a',
        gnomeOrange1:   '#ffbe6f',
        gnomeOrange2:   '#ffa348',
        gnomeOrange3:   '#ff7800',
        gnomeOrange4:   '#e66100',
        gnomeOrange5:   '#c64600',
        gnomeRed1:      '#f66151',
        gnomeRed2:      '#ed333b',
        gnomeRed3:      '#e01b24',
        gnomeRed4:      '#c01c28',
        gnomeRed5:      '#a51d2d',
        gnomePurple1:   '#dc8add',
        gnomePurple2:   '#c061cb',
        gnomePurple3:   '#9141ac',
        gnomePurple4:   '#813d9c',
        gnomePurple5:   '#613583',
        gnomeBrown1:    '#cdab8f',
        gnomeBrown2:    '#b5835a',
        gnomeBrown3:    '#986a44',
        gnomeBrown4:    '#865e3c',
        gnomeBrown5:    '#63452c',
        gnomeLight1:    '#ffffff',
        gnomeLight2:    '#f6f5f4',
        gnomeLight3:    '#deddda',
        gnomeLight4:    '#c0bfbc',
        gnomeLight5:    '#9a9996',
        gnomeDark1:     '#77767b',
        gnomeDark2:     '#5e5c64',
        gnomeDark3:     '#3d3846',
        gnomeDark4:     '#241f31',
        gnomeDark5:     '#000000',
        base:         'var(--color-base)',
        baseAlt:      'var(--color-base-alt)',
        baseContainer:'var(--color-base-container)',
        surface:      'var(--color-surface)',
        onSurface:    'var(--color-on-surface)',
        sidebar:      'var(--color-sidebar)',
        onSidebar:    'var(--color-on-sidebar)',
        primary:      'var(--color-primary)',
        onPrimary:    'var(--color-on-primary)',
        sidebarIcon:  'var(--color-sidebar-icon)',
        'sidebar-icon-active': 'var(--color-sidebar-icon-active)',
        'sidebar-indicator': 'var(--color-sidebar-indicator)',
        'sidebar-text-active': 'var(--color-sidebar-text-active)',
        success:      'var(--gnome-green-5)',
        danger:       'var(--gnome-red-3)',
        warning:      'var(--gnome-yellow-5)',
        info:         'var(--color-primary)',
      },
      borderColor: {
        DEFAULT: 'var(--border-color)',
        primary: 'var(--color-primary)',
        success: 'var(--gnome-green-5)',
        danger:  'var(--gnome-red-3)',
        warning: 'var(--gnome-yellow-5)',
        primarySubtle: 'rgba(53,132,228,0.25)',
      },
      boxShadow: {
        glass:   '0 1px 3px rgba(0,0,0,0.08), 0 1px 2px rgba(0,0,0,0.06)',
        card:    '0 1px 4px rgba(0,0,0,0.08)',
        gnome:   '0 2px 8px rgba(0,0,0,0.12)',
        'gnome-lg': '0 4px 16px rgba(0,0,0,0.15)',
        'gnome-xl': '0 8px 24px rgba(0,0,0,0.18)',
      },
      borderRadius: {
        sm:  '6px',
        DEFAULT: '8px',
        md:  '10px',
        lg:  '12px',
        xl:  '16px',
      },
    },
  },
  plugins: [],
}