-- Create DBA user for external access (pg16)
DO $$
BEGIN
   IF NOT EXISTS (SELECT FROM pg_database WHERE datname = 'expenses') THEN
      CREATE DATABASE expenses;
   END IF;
END
$$;

CREATE USER dba WITH PASSWORD 'DBA_S3cr3t_2026';
GRANT ALL PRIVILEGES ON DATABASE expenses TO dba;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO dba;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO dba;
ALTER USER dba CREATEDB;